- name: Starting the MySQL service
  service:
          name: mysql
          state: restarted
          enabled: yes

- name: Removing the test database
  mysql_db: name=test state=absent

- name: Creating New Database for WordPress
  mysql_db: name={{ wp_db }} state=present

- name: Creating the user for mysql
  mysql_user: user={{ usr }} host="%" password={{ password }} priv=*.*:ALL,GRANT
  no_log: true

- name: Copy .my.cnf file with root password credentials
  copy:
    src: /home/fahad/.my.cnf
    dest: /etc/mysql/my.cnf owner=root mode=0600

- name: Updating mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  no_log: true 
